[pytest]
pythonpath = .
testpaths =
    tests
    stage0/tests
    stage1/tests
    stage2/tests
    stage4/tests
norecursedirs =
    artifacts
    deprecated
    exploratory
    output
    tmp
    .git
