"""Run Stage4 Simulator v3.

This entry point uses the demand-supply decoupled environment generated by the
v2 builder, but executes it through the v3 request-plan-execution kernel.
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

import numpy as np
import pandas as pd

REPO_ROOT = Path(__file__).resolve().parents[2]
if str(REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(REPO_ROOT))

from stage4.simulator_v3.behavior.driver_response import DriverResponseModel
from stage4.simulator_v3.economics import EconomicsModel
from stage4.simulator_v3.entities import RequestState, VehiclePlan, VehicleState
from stage4.simulator_v3.enums import RequestStatus, VehicleExecutionStatus
from stage4.simulator_v3.event_queue import EventQueue
from stage4.simulator_v3.fleet_controller import FleetController
from stage4.simulator_v3.matching.candidate_generator import CandidatePolicy
from stage4.simulator_v3.odd.pickup_odd import PickupODDChecker
from stage4.simulator_v3.odd.service_odd import ServiceODDChecker
from stage4.simulator_v3.plan_validator import PlanValidator
from stage4.simulator_v3.request_manager import RequestManager
from stage4.simulator_v3.routing_engine import RoutingEngine
from stage4.simulator_v3.simulation_engine import SimulationEngine
from stage4.simulator_v3.system_state import SystemState
from stage4.simulator_v3.vehicle_executor import VehicleExecutor


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser()
    parser.add_argument("--replication", type=int, default=1)
    parser.add_argument("--strategy", choices=["Safe GlobalMatch-MinPickup", "ODD-Gated Price-Aware", "Three-Stakeholder Balanced"], default="Safe GlobalMatch-MinPickup")
    parser.add_argument("--operation", default="O0")
    parser.add_argument("--request-time-scenario", choices=["RT-Low", "RT-Base", "RT-High"], default="RT-Base")
    parser.add_argument("--data-root", type=Path, default=Path("stage4/data/decoupled_abm"))
    parser.add_argument("--environment-root", type=Path, default=Path("stage4/output/decoupled_environment"))
    parser.add_argument("--capability", type=Path, default=Path("stage4/output/decoupled_environment/capability_mapping/fold=3/vehicle_capability_mapping.parquet"))
    parser.add_argument("--output-root", type=Path, default=Path("stage4/output/simulator_v3"))
    parser.add_argument("--results-dir", type=Path, default=Path("stage4/docs/results/simulator_v3"))
    parser.add_argument("--profile", default="moderate_av")
    parser.add_argument("--decision-epoch-sec", type=int, default=30)
    parser.add_argument("--max-orders", type=int, default=0, help="0 means full demand stream; positive values are regression smoke subsets.")
    parser.add_argument("--max-vehicles", type=int, default=0, help="0 means full fleet; positive values are regression smoke subsets.")
    parser.add_argument("--min-request-time", default="", help="Optional ISO timestamp for regression smoke windows; full default uses all requests.")
    parser.add_argument("--candidate-maximum", type=int, default=80)
    parser.add_argument("--overwrite", action="store_true")
    return parser.parse_args()


def stress_value(row: pd.Series) -> float:
    if not bool(row.get("condition_available", False)):
        return 0.0
    vals = [row.get("lcs_tail_probability"), row.get("pmis_tail_probability"), row.get("rts_tail_probability")]
    vals = [float(v) for v in vals if pd.notna(v)]
    return float(np.mean(vals)) if vals else 0.0


def load_requests(args: argparse.Namespace) -> dict[str, RequestState]:
    path = args.data_root / f"demand_20161023_{args.request_time_scenario}.parquet"
    frame = pd.read_parquet(path)
    frame = frame.sort_values("simulated_request_time", kind="mergesort")
    if args.min_request_time:
        cutoff = pd.Timestamp(args.min_request_time, tz="UTC") if pd.Timestamp(args.min_request_time).tzinfo is None else pd.Timestamp(args.min_request_time).tz_convert("UTC")
        frame = frame[frame["simulated_request_time"] >= cutoff].copy()
    if args.max_orders and args.max_orders > 0:
        frame = frame.head(args.max_orders).copy()
    requests: dict[str, RequestState] = {}
    for row in frame.itertuples(index=False):
        oid = str(row.order_id)
        request_time = pd.to_datetime(row.simulated_request_time, utc=True)
        latest = request_time + pd.Timedelta(seconds=480)
        req = RequestState(
            order_id=oid,
            request_time=request_time,
            observed_boarding_time=pd.to_datetime(row.observed_boarding_time, utc=True),
            origin_lon=float(row.origin_lon),
            origin_lat=float(row.origin_lat),
            origin_zone=str(row.origin_zone),
            destination_lon=float(row.destination_lon),
            destination_lat=float(row.destination_lat),
            destination_zone=str(row.destination_zone),
            latest_pickup_time=latest,
            condition_available=bool(row.condition_available),
            predicted_service_time_sec=float(row.predicted_service_time_sec),
            realized_service_time_sec=float(row.realized_service_time_sec),
            route_length_m=float(row.route_length_m),
            stress_value=stress_value(pd.Series(row._asdict())),
            metadata={"time_bin": int(row.time_bin), "eta_source": str(row.eta_source)},
        )
        requests[oid] = req
    return requests


def load_vehicles(args: argparse.Namespace) -> dict[str, VehicleState]:
    path = args.environment_root / f"replication={args.replication}" / "simulation_fleet.parquet"
    frame = pd.read_parquet(path).sort_values(["vehicle_type", "online_start", "vehicle_id"], kind="mergesort")
    if args.max_vehicles and args.max_vehicles > 0:
        # Keep all AVs in small smoke tests when possible, then fill with HVs.
        av = frame[frame["vehicle_type"].eq("AV")]
        hv = frame[frame["vehicle_type"].eq("HV")]
        frame = pd.concat([av, hv.head(max(0, args.max_vehicles - len(av)))], ignore_index=True).head(args.max_vehicles)
    vehicles: dict[str, VehicleState] = {}
    for row in frame.itertuples(index=False):
        vid = str(row.vehicle_id)
        empty_plan = VehiclePlan(
            vehicle_id=vid,
            plan_version=0,
            stops=[],
            created_time=pd.to_datetime(row.online_start, utc=True),
            trigger="initialization",
            feasible=True,
            objective_value=0.0,
            assigned_request_ids=[],
            reserved_request_ids=[],
        )
        vehicles[vid] = VehicleState(
            vehicle_id=vid,
            vehicle_type=str(row.vehicle_type),
            current_lon=float(row.initial_lon),
            current_lat=float(row.initial_lat),
            current_zone=str(row.initial_zone),
            online_start=pd.to_datetime(row.online_start, utc=True),
            online_end=pd.to_datetime(row.online_end, utc=True),
            execution_status=VehicleExecutionStatus.OFFLINE,
            current_leg=None,
            active_plan=empty_plan,
            plan_version=0,
            driver_id=None if pd.isna(getattr(row, "driver_id", pd.NA)) else str(getattr(row, "driver_id")),
            session_id=None if pd.isna(getattr(row, "session_id", pd.NA)) else str(getattr(row, "session_id")),
            depot_id=None if pd.isna(getattr(row, "depot_id", pd.NA)) else str(getattr(row, "depot_id")),
            profile=str(getattr(row, "vehicle_profile", "moderate_av")),
        )
    return vehicles


def load_odd(args: argparse.Namespace) -> tuple[PickupODDChecker, ServiceODDChecker]:
    cap = pd.read_parquet(args.capability)
    cap = cap[(cap["vehicle_profile"].eq(args.profile)) & cap["vehicle_type"].eq("AV")]
    cap_map = {str(r.order_id): r._asdict() for r in cap.itertuples(index=False)}
    pickup = pd.read_parquet(args.data_root / "pickup_odd_zone_pair_proxy.parquet")
    pickup_map = {(str(r.origin_zone), str(r.destination_zone)): bool(r.pickup_odd_feasible) for r in pickup.itertuples(index=False)}
    return PickupODDChecker(pickup_map), ServiceODDChecker(cap_map)


def run(args: argparse.Namespace) -> dict:
    requests = load_requests(args)
    vehicles = load_vehicles(args)
    if not requests:
        raise ValueError("No requests loaded.")
    start = min(r.request_time for r in requests.values()).floor(f"{args.decision_epoch_sec}s")
    latest_request = max(r.request_time for r in requests.values())
    max_service = max(r.realized_service_time_sec for r in requests.values())
    end = latest_request.ceil(f"{args.decision_epoch_sec}s") + pd.Timedelta(seconds=480 + max_service + 1800)
    state = SystemState(current_time=start, requests=requests, vehicles=vehicles)
    events = EventQueue()
    routing = RoutingEngine(args.data_root)
    pickup_odd, service_odd = load_odd(args)
    validator = PlanValidator(pickup_odd, service_odd)
    economics = EconomicsModel()
    driver_response = DriverResponseModel()
    controller = FleetController(
        routing,
        validator,
        economics,
        driver_response,
        CandidatePolicy(maximum_candidates=args.candidate_maximum),
    )
    executor = VehicleExecutor(routing, events)
    engine = SimulationEngine(state, events, controller, executor, RequestManager(), decision_epoch_sec=args.decision_epoch_sec)
    engine.configure_strategy(args.strategy)
    engine.initialize_events(start, end)
    summary = engine.run(end)
    out = args.output_root / f"replication={args.replication}" / f"strategy={args.strategy.replace(' ', '_')}" / f"operation={args.operation}" / args.request_time_scenario
    if out.exists() and not args.overwrite:
        raise FileExistsError(f"{out} exists; pass --overwrite")
    engine.write_outputs(out)
    args.results_dir.mkdir(parents=True, exist_ok=True)
    summary.update({
        "replication_id": args.replication,
        "strategy": args.strategy,
        "operation": args.operation,
        "request_time_scenario": args.request_time_scenario,
        "max_orders": args.max_orders,
        "max_vehicles": args.max_vehicles,
        "output_path": str(out),
    })
    summary_path = args.results_dir / "simulator_v3_strategy_summary.csv"
    new = pd.DataFrame([summary])
    if summary_path.exists():
        old = pd.read_csv(summary_path)
        new = pd.concat([old, new], ignore_index=True)
    new.to_csv(summary_path, index=False)
    (out / "summary.json").write_text(json.dumps(summary, indent=2), encoding="utf-8")
    return summary


def main() -> None:
    args = parse_args()
    summary = run(args)
    print(json.dumps(summary, indent=2))


if __name__ == "__main__":
    main()
