"""Enums for the request-plan-execution simulator."""

from __future__ import annotations

from enum import Enum


class RequestStatus(str, Enum):
    UNREVEALED = "UNREVEALED"
    PENDING = "PENDING"
    CANDIDATE_SELECTED = "CANDIDATE_SELECTED"
    OFFERED = "OFFERED"
    RESERVED = "RESERVED"
    ASSIGNED = "ASSIGNED"
    PICKUP_PENDING = "PICKUP_PENDING"
    PICKUP_STARTED = "PICKUP_STARTED"
    BOARDED = "BOARDED"
    IN_SERVICE = "IN_SERVICE"
    COMPLETED = "COMPLETED"
    CANCELLED = "CANCELLED"


class VehicleExecutionStatus(str, Enum):
    OFFLINE = "OFFLINE"
    IDLE = "IDLE"
    WAITING = "WAITING"
    PICKUP = "PICKUP"
    BOARDING = "BOARDING"
    SERVICE = "SERVICE"
    DROPOFF = "DROPOFF"
    REPOSITIONING = "REPOSITIONING"
    REBALANCING = "REBALANCING"


class StopType(str, Enum):
    WAIT = "WAIT"
    PICKUP = "PICKUP"
    BOARD = "BOARD"
    SERVICE_END = "SERVICE_END"
    DROP_OFF = "DROP_OFF"
    HV_REPOSITION = "HV_REPOSITION"
    AV_REBALANCE = "AV_REBALANCE"
    RETURN_DEPOT = "RETURN_DEPOT"
    OFFLINE = "OFFLINE"


class LegType(str, Enum):
    PICKUP = "PICKUP"
    SERVICE = "SERVICE"
    HV_REPOSITION = "HV_REPOSITION"
    AV_REBALANCE = "AV_REBALANCE"
    WAIT = "WAIT"


class EventType(str, Enum):
    LEG_COMPLETED = "LEG_COMPLETED"
    SERVICE_COMPLETED = "SERVICE_COMPLETED"
    HV_SESSION_END = "HV_SESSION_END"
    HV_SESSION_START = "HV_SESSION_START"
    REQUEST_REVEALED = "REQUEST_REVEALED"
    DRIVER_RESPONSE = "DRIVER_RESPONSE"
    RESERVATION_EXPIRED = "RESERVATION_EXPIRED"
    PLAN_INVALIDATED = "PLAN_INVALIDATED"
    DECISION_EPOCH = "DECISION_EPOCH"


class DriverResponse(str, Enum):
    ACCEPT = "ACCEPT"
    REJECT = "REJECT"
    TIMEOUT = "TIMEOUT"

